spark-on-yarn:
  environment:
    TEST_ENV1: bigdata
    TEST_ENV2: ${WORKER_NUM} 
    TEST_ENV3: ${environment_name}
    TEST_ENV4: $${stack_name}
    TEST_ENV5: ${stack_name}
  net: "host"
  labels:
    io.rancher.scheduler.global: 'true'
  image: markyeh/spark-on-yarn:v0.0.0
  volumes:
  - /data/hdfs:/home/hadoop/hadoop/tmp
  - /var/lib/nvidia-docker/volumes/nvidia_driver/361.45.18:/usr/local/nvidia:ro
  privileged: true